### ISSUE TITLE
BME280 statt DHT22

### ISSUE THREAD

**Issue by ohobby** [verschwoerhaus/ttn-ulm-feinstaub#7]
Hi,

wäre es nicht besser einen BME280 statt DHT22 zu nutzen? Was müsste man am Code ändern und wie würde sich der Anschluß ändern?

Grüße,
Oliver

**Comment by Octoate** [comment]
Hi,
ich habe die BME280 Unterstützung eingebaut. Wenn der Pull Request #8 gemerged wird, ist die Unterstützung mit drin.

CU Tim

**Comment by stkdiretto** [comment]
Danke @Octoate!
